# Generated by Django 3.1.1 on 2020-10-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_reason',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('liked', 'Liked'), ('disliked', 'Disliked'), ('commented', 'Commented'), ('replied', 'replied'), ('follow', 'Follow'), ('unfollow', 'Unfollowed')], default='welcome', max_length=50),
        ),
    ]
